inventory:
    resource: "@InventoryBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

inventory_new:
    path:      /new/{id}
    defaults:  { _controller: InventoryBundle:Inventory:new }
    requirements:
        number: \d+